name: FetchMeetup

on:
  schedule:
    - cron: '45 8 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch Data from Meetup
      run: | 
        cd hyde
        lein deps
        lein run
        cd ..

    - name: Generierte Daten kopieren
      run: | 
        pwd
        cp -r hyde/jekyll/_data/* jekyll/_data/
        cp -r hyde/jekyll/_posts/* jekyll/_posts/
        cp -r hyde/jekyll/_includes/* jekyll/_includes/
  
   
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: jekyll
        
