name: FetchMeetup

on:
  schedule:
    - cron: '45 8 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'

    - name: Neue Veranstaltungen mit Mr Poole übersetzen
      run: | 
        cd mr_poole
        ./gradlew -version
        ./gradlew run
        ls output
        ls output/mds
        cd ..
    
    - name: Fetch Data from Meetup
      run: | 
        cd hyde
        lein deps
        lein run
        cd ..

    - name: Generierte Daten kopieren
      run: | 
        find mr_poole/output/mds -type f -exec cp -rf {} jekyll/_newposts \;
        cp -f mr_poole/output/veranstaltungen.zip jekyll/files/extern
        cp -f mr_poole/output/uebersicht.xml jekyll/files/extern
        cp -rf hyde/jekyll/_data/* jekyll/_data/
        cp -rf hyde/jekyll/_posts/* jekyll/_posts/
        cp -rf hyde/jekyll/_includes/* jekyll/_includes/
  
   
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: jekyll
        
